### ISSUE TITLE
fork link on learnco doesn't work ...404 error

### ISSUE THREAD

**Issue by kev112** [learn-co-curriculum/js-dom-and-events-hide-and-seek-lab#3]
fork link on learnco doesn't work ...404 error

**Comment by drakeltheryuujin** [comment]
Hi @kev112! This request sounds like an issue with the Learn platform.
[Raising issues on GitHub][raise] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.). Iif Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
