### ISSUE TITLE
lab doesnt open 

### ISSUE THREAD

**Issue by nicoleeidi** [learn-co-curriculum/js-dom-and-events-hide-and-seek-lab#4]
The fork link to github doesnt work. Student found the lab on github, when he forks it, it doesnt connect back with his learn page or show a green light.

**Comment by drakeltheryuujin** [comment]
Hi @kev112! This request sounds like an issue with the Learn platform.
[Raising issues on GitHub][raise] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.). Iif Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
