### ISSUE TITLE
person.greet()(); // two parentheses used here to invoke the returned function

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/js-dom-and-events-hide-and-seek-lab#7]
to display the expected console messages,*1, one will have to 
1. either install node, and issue node command, and copy and paste the codes above it  OR
2. in chrome, one will have to click on "other" in user messages under sidebar, to display the console messages. Otherwise, in my case I will only see the result of the evaluation and not the console.log() messages.

**Comment by sgharms** [comment]
I don't see any reference to the word `greet` in the readme for this lab. Are you sure this is the proper repository?

**Comment by sgharms** [comment]
I'm going to close this pending your reply. Please clarify.

**Comment by ICanDoAllThingThroughChrist** [comment]
The method call d tests for unique meal by neighborhood is too difficult

**Comment by sgharms** [comment]
@ICanDoAllThingThroughChrist 

I'm confused. Why are you talking about meals in this repository? Your original issue was around a function called `greet` which, doesn't appear in any file in this repository.  For the record, the word meal doesn't show up either:

```sh
➜  ~ cd /tmp
➜  /tmp git clone git@github.com:learn-co-curriculum/js-dom-and-events-hide-and-seek-lab.git
Cloning into 'js-dom-and-events-hide-and-seek-lab'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 126 (delta 18), reused 33 (delta 15), pack-reused 81
Receiving objects: 100% (126/126), 52.88 KiB | 1.23 MiB/s, done.
Resolving deltas: 100% (53/53), done.
➜  /tmp cd js-dom-and-events-hide-and-seek-lab
➜  js-dom-and-events-hide-and-seek-lab git:(master) ls
CONTRIBUTING.md   README.md         index.js          package.json
LICENSE.md        index.html        package-lock.json test
➜  js-dom-and-events-hide-and-seek-lab git:(master) grep -Ri greet *
➜  js-dom-and-events-hide-and-seek-lab git:(master) grep -Ri meal *
➜  js-dom-and-events-hide-and-seek-lab git:(master) git show  |head -1
commit c50721f83aefcf67d7d6d9e355979f294d71896c
```

So as of commit c50721f83aefcf67d7d6d9e355979f294d71896c I see no reference to either the word `greet` or `meal`.

So, can you please clarify what is wrong, perhaps using specific filenames and line numbers would help?

**Comment by ICanDoAllThingThroughChrist** [comment]
The issue is not the subject, but the environment.I am not sure how the subject is inserted into this problem

**Comment by sgharms** [comment]
@ICanDoAllThingThroughChrist 

OK that's helpful. I'll disregard the subject.

Which "expected console messages" are you referring to? Please provide to specific filenames and line numbers as, as of c50721f there is no occurrence of the word console in this repository at all, except for this line 53 in `index.html` as shown below.

```sh
➜  js-dom-and-events-hide-and-seek-lab git:(master) ack console
index.html
53:    <!-- Open this file and call `mocha.run()` in console to run tests -->
```

**Comment by ICanDoAllThingThroughChrist** [comment]
I typically write console.log (). In my code and thus not in spec tests. This is a more general environment issue

**Comment by sgharms** [comment]
1. You do not need node to complete this lab. So let's rule that out.
2. It sounds like this issue is in your development environment. We can help you optimize your process so that you can see the messages where you expect them. Have you tried discussing this via Ask A Question/

**Comment by sgharms** [comment]
@ICanDoAllThingThroughChrist I thought I'd follow-up on this. Were you able to get help on this issue?

**Comment by ICanDoAllThingThroughChrist** [comment]
Let us close the issue. I have resolved to just read the solutions branch like a recipe book instead. 3rd yr into the course on part time basis.
